### ISSUE TITLE
OCR on sentences

### ISSUE THREAD

**Issue by prolaser** [githubharald/SimpleHTR#2]
Hey there

Thank you for uploading your model it is really useful for me to understand the concept of using CNN+LSTM architecture. I wanted to know if it is also possible to apply this model on IAM sentences instead of characters.Have you tried it your self?and if so how was the accuracy on the testset?

**Comment by githubharald** [comment]
Hi,

there was a similar question on medium, I link to the answer:
https://medium.com/@harald_scheidl/hi-193e814f93c3

So, in short, the model provided with this repository is too small for complete text-lines (otherwise, CPU training would not be possible).
For the larger model described in the link above I measured the accuracy with CER* and WER* on the test-set and got 8.95% for CER and 25.01% for WER.

\* Character Error Rate and Word Error Rate
