### ISSUE TITLE
cv2.imread on corrupted image file terminates program with std::out_of_range error

### ISSUE THREAD

**Issue by Chazzz** [githubharald/SimpleHTR#25]
Relevant Versions: Ubuntu 18.10, Python 2.7.15, python-opencv 3.2.0. Experienced when running `python main.py --train`.

Error message:
>terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 140) > this->size() (which is 0)
Aborted (core dumped)

Further debugging revealed the terminate is called directly after trying to read a corrupted image file such as r06-022-03-05.png

**Adding a try-except clause does not resolve the issue. The process still terminates.**

Fix: in src/DataLoader.py, imageio was imported and the getNext was modified as follows:

>
		imgs = []
		for i in batchRange:
			try:
				img = imageio.imread(self.samples[i].filePath)
			except ValueError:
				img = np.zeros([self.imgSize[1], self.imgSize[0]])
			imgs.append(preprocess(img, self.imgSize, self.dataAugmentation))
		# imgs = [preprocess(cv2.imread(self.samples[i].filePath, cv2.IMREAD_GRAYSCALE), self.imgSize, self.dataAugmentation) for i in batchRange]

I assume imageio is also functional with python 3 however it's not clear whether adding a dependency to imageio is desirable across all versions of SimpleHTR.

**Comment by githubharald** [comment]
thanks for reporting this. 
Interestingly, on my machine imread (OpenCV 3.0.0) returns None in case of damaged images (even if I use Python 2.7.12). I handled these damaged images in the function [preprocess](https://github.com/githubharald/SimpleHTR/blob/master/src/SamplePreprocessor.py#L10). 

OpenCV doc say the following about imread:

> The function imread loads an image from the specified file and returns it. If the image cannot be read (because of missing file, improper permissions, unsupported or invalid format), the function returns an empty matrix ( Mat::data==NULL ).

So, even though they talk about the C++ API, they say that damaged images yield empty matrices (which might be translated to None in Python). So there shouldn't be any crash. 


Now the question is: why is your imread not returning None but crashing the program? I don' think that this is the desired behaviour. What happens if you try to open the damaged image directly from the Python 2.7 interactive interpreter: 
`>>> print(cv2.imread('r06-022-03-05.png'))`
It simply prints None on my machine.

As a work-around, I would suggest checking for damaged files (files with 0 size) directly when reading the file words.txt, e.g. by adding the following code [just before adding the word to the list of samples](https://github.com/githubharald/SimpleHTR/blob/master/src/DataLoader.py#L52). This way, the check is only done once at the beginning of training.

```python
# check if image is not empty
if not os.path.getsize(fileName):
	print('damaged img file:', fileName)
	continue
```
It outputs the following two damaged files on my machine which won't be used for training now:
damaged img file: ../data/words/a01/a01-117/a01-117-05-02.png
damaged img file: ../data/words/r06/r06-022/r06-022-03-05.png

**Comment by Chazzz** [comment]
Thanks for the detailed response. Based on the docs, sounds like a bug in cv2. Your proposed workaround resolves the cv2.imread issue on my system, and is significantly more mergable than my fix. My only suggestion would be to indicate to the user that the 2 damaged image files being detected is expected behaviour.

**Comment by githubharald** [comment]
merged your PR and I additionally used __future__ for print and division. Please let me know if you encounter any more problems with Python 2.

**Comment by Chazzz** [comment]
Good idea. Builds and runs without errors.
