### ISSUE TITLE
Works only for single word

### ISSUE THREAD

**Issue by IamDixit** [githubharald/SimpleHTR#9]
Hi,
Is this model only works for single handwritten word?
When the image has a collection of multiple words (a sentence) then this model gives poor/no result. But when the image has only one word like (Cat), this model works perfectly. Is my observation is correct or am I missing something here?
Thanks.

**Comment by githubharald** [comment]
Hi,

yes, that's correct. The reason is not the number of words, but the size of the input image.
The input image is downsized to 128x32px, so if it contains a long sentence you won't be able to read the text on it anymore.
However, groups of short words should work fine, e.g. "I go home".

For more information see section 2 of this article: https://towardsdatascience.com/27648fb18519

**Comment by IamDixit** [comment]
If my image size is fixed to 128x32 for each input, I guess then multiple
words will be read properly.
Will this approach work?

**Comment by githubharald** [comment]
There is no need to resize your input to 128x32, this is done automatically (also taking care that no distortion happens). You just have to take care that in your image, when downsized, the text is still large enough to be recognized. 
I recommend either approach 2.1 or 2.2 of the linked article.

**Comment by IamDixit** [comment]
Thank you so much for the guidance

**Comment by IamDixit** [comment]
You are right, using word segmentation I am getting correct results.

**Comment by githubharald** [comment]
Is the writing style for you alhpnum images the same as for your "normal" text?
Just to be sure that the bad results are not just because the writing looks entirely different. 

If it's not the writing style: maybe the model learned some language properties, such that certain character combinations are more likely than others, e.g. "na" is more likely than "nx" in the IAM dataset which the model was trained on. But this is just an assumption, I didn't do any experiments to check if this is really the case.

**Comment by PartheshSoni** [comment]
How can I train your network for some other language like Hindi??
